[master]
13.61.25.230 ansible_user=ubuntu ansible_ssh_private_key_file=~/k8s-key.pem

[worker]
13.48.46.222 ansible_user=ubuntu ansible_ssh_private_key_file=~/k8s-key.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'